# Generated by Django 5.1.1 on 2024-10-12 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='tasks',
        ),
        migrations.AddField(
            model_name='tasks',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
    ]
