# Generated by Django 5.1.1 on 2024-10-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_patient_tasks_tasks_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
