# Generated by Django 5.1.1 on 2024-10-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
